[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.23"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
ethereum = "${ETH_RPC_URL}"
polygon = "${POL_RPC_URL}"
bsc = "${BNB_RPC_URL}"
arbitrum = "${ARB_RPC_URL}"
avalanche = "${AVAX_RPC_URL}"
optimism = "${OPT_RPC_URL}"
celo = "${CELO_RPC_URL}"
klaytn = "${KLAY_RPC_URL}"

[etherscan]
ethereum = { key = "${ETH_API_KEY}", chain = "mainnet" }
polygon = { key = "${POL_API_KEY}", chain = "polygon" }
bsc = { key = "${BNB_API_KEY}", chain = "bsc" }
arbitrum = { key = "${ARB_API_KEY}", chain = "arbitrum" }
avalanche = { key = "${AVAX_API_KEY}", chain = "avalanche" }
optimism = { key = "${OPT_API_KEY}", chain = "optimism" }
celo = { key = "${CELO_API_KEY}", chain = "celo" }
